/*
 * MOBRIC CONFIDENTIAL
 * ___________________
 *
 * 2013 Mobric Incorporated
 * All Rights Reserved.
 *
 * NOTICE:
 * All information contained herein is, and remains the property of
 * Mobric Incorporated and its suppliers, if any. Dissemination of this
 * information or reproduction of this material is strictly forbidden unless
 * prior written permission is obtained from Mobric Incorporated.
 *
 */

#ifndef ERR_CODE_H
#define ERR_CODE_H

/*
 *	-----------------------------------
 *	| error | level | category | type |
 *	-----------------------------------
 *  32      31      28         14     0
 *
 */

#define MAKE_ERR(err, lv, cat, type) ((err << 31) | (lv << 28) | (cat << 14) | type)

enum {
	ERR_LV_DBG,
	ERR_LV_INFO,
	ERR_LV_WARN,
	ERR_LV_ERR
};

enum {
	ERR_CAT_GENERAL,
	ERR_CAT_DAEMON,
	ERR_CAT_DPM_CFG,
	ERR_CAT_MSG,
	ERR_CAT_NET
};

#define DIN_NO_ERR						MAKE_ERR(0, ERR_LV_DBG,		ERR_CAT_GENERAL,	0x00)
#define DIN_OPEN_FILE_FAIL				MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_GENERAL, 	0x01)
#define DIN_READ_FILE_FAIL				MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_GENERAL, 	0x02)
#define DIN_CHANGE_DIR_FAIL				MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_GENERAL, 	0x03)
#define DIN_INVALID_PARAM				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_GENERAL, 	0x04)
#define DIN_OUT_OF_BOUND				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_GENERAL,	0x05)
#define DIN_REGEX_COMP_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_GENERAL,	0x06)
#define DIN_CREATE_THREAD_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_GENERAL,	0x07)
#define DIN_UNKNOWN_ERR					MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_GENERAL,	0x08)
#define DIN_PIPE_OPT_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_GENERAL,	0x09)

#define DIN_DAEMON_ALREADY_EXISTS		MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_DAEMON, 	0x00)
#define DIN_FORK_PROC_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_DAEMON, 	0x01)
#define DIN_CREATE_SESSION_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_DAEMON,		0x02)
#define DIN_CREATE_DAEMON_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_DAEMON,		0x03)

#define DIN_LOAD_DPM_CFG_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_DPM_CFG,	0x00)
#define DIN_CFG_KEY_NOT_FOUND			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_DPM_CFG,	0x01)

#define DIN_CREATE_SOCK_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x00)
#define DIN_BIND_ADDR_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x01)
#define DIN_SELECT_SOCK_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x02)
#define DIN_RECV_DATA_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x03)
#define DIN_RECV_LEN_MISMATCHED			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x04)
#define DIN_SEND_DATA_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x05)
#define DIN_SEND_EVENT_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x06)
#define DIN_SEND_CMD_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x07)
#define DIN_SEND_REMOTE_MSG_FAIL		MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x08)
#define DIN_DC_NOT_REG					MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_MSG,		0x09)
#define DIN_DC_NOT_RECOG				MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_MSG,		0x0A)
#define DIN_UNKNOWN_MSG					MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_MSG,		0x0B)
#define DIN_SEARCH_SERVER_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x0C)
#define DIN_CMD_NOT_RECOG				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x0D)
#define DIN_HANDSHAKE_FAIL				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x0F)
#define DIN_SEARCH_NOT_YET_FINISHED		MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_MSG,		0x10)
#define DIN_CONTENT_TOO_LARGE			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x11)
#define DIN_REMOTE_MSG_TIMEOUT			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x12)
#define DIN_REMOTE_MSG_CHKSUM_ERR		MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x13)
#define DIN_INVALID_REMOTE_MSG			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x14)
#define DIN_LATENCY_TEST_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x15)
#define DIN_SEND_CONN_HISTORY_INFO_FAIL	MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MSG,		0x16)

#define DIN_ITEM_NOT_FOUND				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MAP,		0x00)
#define DIN_ITEM_ALREADY_EXISTS			MAKE_ERR(1, ERR_LV_WARN,	ERR_CAT_MAP,		0x01)
#define DIN_MAP_OUT_OF_SPACE			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MAP,		0x02)
#define DIN_VALUE_TOO_LARGE				MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_MAP,		0x03)

#define DIN_QUERY_SERVER_ADDR_FAIL		MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_NET,		0x00)
#define DIN_QUERY_TXT_REC_FAIL			MAKE_ERR(1, ERR_LV_ERR,		ERR_CAT_NET,		0x01)

#endif
